QUOTES = [
    "You think we practice until we get it right. I think we practice until we can't get it wrong.",
    "High achievers don’t like mediocre people and mediocre people don’t like high achievers",
    "Everybody wants to be the beast, but everybody don't want to do what the beasts do.",
    "There are two pains in life. There is the pain of discipline and the pain of disappointment. If you can handle the pain of discipline, then you'll never have to deal with the pain of disappointment.",
    "Yall don’t remember the Georgia Southern game, do you? I don’t think we had a guy on that field that didn’t play in the NFL and about 4 or 5 of em were first round draft picks, and I think that team won a national championship, but I’m not sure. And they ran through our ass like shit through a tin horn and we could not stop em, could not stop em",
    "What happened yesterday is history. What happens tomorrow is a mystery. What we do today makes a difference",
    "Eliminate the clutter and all of the things that are going on outside and focus on the things that you can control with how you go about and take care of your business. Take the other team out of the game and make it all about you and what you do.",
    "Process guarantees success. A good process produces good results",
    "As bad as you think you want to win it. I promise you the guys that go out there and work every day ... they want to win it more than that. And I'm going to feel a hell of a lot worse for them than you if they don't",
    "I don't think it's about who you play, I think it's about who you are",
    "You can blame the other guy for saying it, or you can look at yourself and say, 'I must have contributed to this.",
    "There were no arguments, those are called ass-chewings.",
    "I loved it at LSU",
    "Talent is putting good skills to use",
    "Great leaders are not always popular",
    "I always ask myself the question, do you like to win, or do you hate to lose?",
    "One thing about championship teams is that they’re resilient. No matter what is thrown at them, no matter how deep the hole, they find a way to bounce back and overcome adversity.",
    "Everybody hits me up for eating Little Debbies, but no one passes that cookie jar without taking one.",
    "Passion always looks like aggression to the unmotivated.",
]
